### ISSUE TITLE
Feature Request: fetch issues by environment

### ISSUE THREAD

**Issue by hu-chia** [sparkmeter/sentry2csv#20]
Is there a way to fetch issues from a certain environment?

**Comment by arusahni** [comment]
Hi, thanks for reaching out! You are correct - this cannot be done at the moment. However, this seems like a straightforward and reasonable thing for us to support.

For your use case, could you describe what your ideal input would be (e.g. an argument with a string), and whether or not you'd expect the environment name to be printed in the CSV output?

**Comment by hu-chia** [comment]
Ideally, my input should be `--environment production`, and the environment name couldn't be printed in the CSV output, unless my input is a regex. BTW, the CSV output should print the last event time of an issue.

**Comment by arusahni** [comment]
Hi! Support for the `--environment` parameter has been added in the newly-published v1.3.0 release. Thanks for the feature request.
